--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/fernanACM/SizeUI
build-by-default: true
branches:
- PM5
- main
projects:
  SizeUI:
    path: ""
    icon: icon.png
    lint:
      phpstan: false
...
