name: SizeUI
main: fernanACM\SizeUI\SizeUI
version: 2.0.1
api: 5.3.0
author: fernanACM
website: https://github.com/fernanACM

permissions:
  sizeui.acm:
    default: op
    description: Permission of SizeUI /size
  sizeui.manage.acm:
    description: Permission of /size manage